os: linux
dist: focal
language: python
python: "3.7"

addons:
  apt:
    packages:
    - g++-10
    - gcc-10
    - ruby2.7
    - libopenblas-dev
    - liblapack-dev
    - lcov
    - cmake
    - libeigen3-dev
    - libdune-common-dev
  
matrix:
  include:
    # LINUX
    # GCC 10
    - os: linux
      env: COMPILER=g++-10 COMPUTE_COVERAGE=true
      compiler: gcc
      
     
install:
  - export CXX=${COMPILER}
  - pip install conan
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${COMPUTE_COVERAGE}" == "true" ]]; then
      sudo gem install coveralls-lcov
    fi


script:
  - mkdir build && cd build
  - conan install .. --profile ../conanprofile.txt --build missing
  - cmake -DFuncy_BuildTest=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake ..
  - |
    if [[ "${COMPUTE_COVERAGE}" == "true" ]]; then
      cmake .. -DFuncy_BuildTest=ON -DFuncy_DisableAssert=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-coverage"
    else
      cmake .. -DFuncy_BuildTest=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
    fi
  - cmake --build .
  - cd test && ctest


after_success:
  ############################################################################
  # Upload coverage information to coveralls.io
  ############################################################################
  - |
    if [[ "${COMPUTE_COVERAGE}" == "true" ]]; then
      lcov --gcov-tool gcov-10 --capture --no-external --directory . --base-directory ${TRAVIS_BUILD_DIR}/include -rc lcov_branch_coverage=1 --output-file coverage.info
      coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info
    fi

