name: CMake

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        compiler_version: [10]
        include:
          - build_type: Debug
            cc: gcc-10
            cxx: g++-10
            gcov: gcov-10
            compiler: gcc
            compiler_version: 10
            cxx_flags: -coverage
          - build_type: Release
            cc: clang-10
            cxx: clang++-10
            compiler: clang
            compiler_version: 10

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: srt32/git-actions@v0.0.3

    - name: Set ENV variables
      run: |
        echo "COMPILER=${{matrix.compiler}}" >> $GITHUB_ENV
        echo "COMPILER_VERSION=${{matrix.compiler_version}}" >> $GITHUB_ENV
        echo "CXX=${{matrix.cxx}}" >> $GITHUB_ENV
        echo "CC=${{matrix.cc}}" >> $GITHUB_ENV
        echo "GCOV=${{matrix.gcov}}" >> $GITHUB_ENV
        echo "BUILD_TYPE=${{matrix.build_type}}" >> $GITHUB_ENV
        echo "COVERALLS_TOKEN=${{secrets.COVERALLS_TOKEN}}" >> $GITHUB_ENV
        echo "FLAGS=${{matrix.cxx_flags}}" >> $GITHUB_ENV

    - name: Print ENV vars
      run: |
        echo "COMPILER: ${COMPILER}"
        echo "COMPILER_VERSION: ${COMPILER_VERSION}"
        echo "CXX: ${CXX}"
        echo "CC: ${CC}"
        echo "GCOV: ${GCOV}"
        echo "BUILD_TYPE: ${BUILD_TYPE}"

    - name: Run unit tests
      run: docker run --rm -u $UID -v ${PWD}:/home/funcy -w /home/funcy lubkoll/funcy /bin/bash scripts/run_tests.sh $COMPILER $COMPILER_VERSION $BUILD_TYPE $FLAGS $COVERALLS_TOKEN

