name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
#    name: ${ { matrix.config.name } }
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - build_type: Release
            cc: gcc-10
            cxx: g++-10
            gcov: gcov-10
            compiler: gcc
          - build_type: Release
            cc: clang-9
            cxx: clang++-9
            compiler: clang
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set ENV variables
      run: |
        echo "::set-env name=COMPILER::${{matrix.compiler}}"
        echo "::set-env name=CXX::${{matrix.cxx}}"
        echo "::set-env name=CC::${{matrix.cc}}" 

    - name: Print Travis ENV vars 
      run: |
        echo "COMPILER: ${COMPILER}"
        echo "CXX: ${CXX}"
        echo "CC: ${CC}"

    - name: Setup
      run: |
        pip install conan
        conan profile new default --detect
        conan profile update settings.compiler=$COMPILER default
        conan profile update settings.compiler.libcxx=libstdc++11 default
        conan profile update settings.build_type=$BUILD_TYPE default

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Install Dependencies
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: conan install $GITHUB_WORKSPACE --build missing

    - name: Configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DFuncy_BuildTest=ON -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash

      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build/test
      shell: bash
      run: ctest -C $BUILD_TYPE
